x1 = 0;
x2 = 0;
x3 = 0;
x4 = 0;
u = @(t)t;
t = 1;
%%
H = [ 0, 0,                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                        0;
 1, 0,                                                                                                                                                                             -(cos(x3) + 1)/(cos(x3)^2 + 1),                                                                                                                                                                                                                                                                                              (cos(x3)*(cos(x3) + 1))/(cos(x3)^2 + 1) - 1;
 0, 0, - (cos(x3) + u(t)*sin(x3) + x4^2*cos(x3)^2 - x4^2*sin(x3)^2 - x2*sin(x3))/(cos(x3)^2 + 1) - (2*cos(x3)*sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - u(t)*(cos(x3) - 1)))/(cos(x3)^2 + 1)^2, (cos(x3)*(cos(x3) + u(t)*sin(x3) + x4^2*cos(x3)^2 - x4^2*sin(x3)^2 - x2*sin(x3)))/(cos(x3)^2 + 1) - (sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - u(t)*(cos(x3) - 1)))/(cos(x3)^2 + 1) - x4^2*cos(x3) + (2*cos(x3)^2*sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - u(t)*(cos(x3) - 1)))/(cos(x3)^2 + 1)^2;
 0, 1,                                                                                                                                                                    -(2*x4*cos(x3)*sin(x3))/(cos(x3)^2 + 1),                                                                                                                                                                                                                                                                                  (2*x4*cos(x3)^2*sin(x3))/(cos(x3)^2 + 1) - 2*x4*sin(x3)];

% Z = [ 0, 0,                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                          0;
%  1, 0,                                                                                                                                                                                         -(cos(x3) + 1)/(cos(x3)^2 + 1),                                                                                                                                                                                                                                                                                                                (cos(x3)*(cos(x3) + 1))/(cos(x3)^2 + 1) - 1;
%  0, 0, - (cos(x3) + x4^2*cos(x3)^2 - x4^2*sin(x3)^2 + conj(u)*sin(x3) - x2*sin(x3))/(cos(x3)^2 + 1) - (2*cos(x3)*sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - conj(u)*(cos(x3) - 1)))/(cos(x3)^2 + 1)^2, (cos(x3)*(cos(x3) + x4^2*cos(x3)^2 - x4^2*sin(x3)^2 + conj(u)*sin(x3) - x2*sin(x3)))/(cos(x3)^2 + 1) - (sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - conj(u)*(cos(x3) - 1)))/(cos(x3)^2 + 1) - x4^2*cos(x3) + (2*cos(x3)^2*sin(x3)*(cos(x3)*sin(x3)*x4^2 + sin(x3) + x2*(cos(x3) + 1) - conj(u)*(cos(x3) - 1)))/(cos(x3)^2 + 1)^2;
%  0, 1,                                                                                                                                                                                -(2*x4*cos(x3)*sin(x3))/(cos(x3)^2 + 1),                                                                                                                                                                                                                                                                                                    (2*x4*cos(x3)^2*sin(x3))/(cos(x3)^2 + 1) - 2*x4*sin(x3)]